language: node_js
node_js:
  - '5'
  - '4'
before_script:
- curl -X POST https://codeclimate.com/github/LivelyKernel/lively4-serviceworker/refresh
after_script:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < coverage/lcov.info
